version: '3.9'
services:

  hotel:
    build: .
    container_name: hotel_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hotel/:/usr/src/app/
    ports:
      - "8080:8000"
    env_file:
      - ./hotel/.env.dev
    depends_on:
      - hotel_db

  hotel_db:
    image: postgres:14.5-alpine
    container_name: hotel_db
    volumes:
      - hotel_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hotel
      - POSTGRES_PASSWORD=hotel
      - POSTGRES_DB=hotel_db
    ports:
      - "5432:5432"

  portal:
    build: .
    container_name: portal_django
    volumes:
      - ./webportal/:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./webportal/.env.dev
    depends_on:
      - portal_db

  portal_db:
    image: postgres:14.5-alpine
    container_name: portal_db
    volumes:
      - portal_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
      - POSTGRES_DB=portal_db
    ports:
      - "30432:5432"

  hotel_channels:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  hotel_db:
  portal_db:
