# Generated by Django 4.0.5 on 2022-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('checkin_date', models.DateField(verbose_name='Дата заселения')),
                ('checkout_date', models.DateField(verbose_name='Дата выселения')),
                ('room', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
