# Generated by Django 4.0.5 on 2022-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.FloatField()),
                ('icon', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
