# Generated by Django 4.0.5 on 2022-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_guest_email_alter_guest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ManyToManyField(to='registration.guest', verbose_name='Гость'),
        ),
    ]
