# Generated by Django 4.0.5 on 2022-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_booking_guest_booking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Номер'),
        ),
    ]
