# Generated by Django 4.0.5 on 2022-06-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Номер')),
                ('light', models.JSONField(verbose_name='Свет')),
                ('climat', models.JSONField(verbose_name='Климат')),
            ],
            options={
                'verbose_name': 'Автоматизация номера',
                'verbose_name_plural': 'Автоматизация номеров',
            },
        ),
    ]
