# Generated by Django 4.0.5 on 2022-06-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_automation', '0002_alter_roomautomation_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomautomation',
            old_name='room_number',
            new_name='room',
        ),
    ]
