# Generated by Django 4.0.5 on 2022-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_automation', '0003_rename_room_number_roomautomation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomautomation',
            name='room',
        ),
        migrations.AddField(
            model_name='roomautomation',
            name='number',
            field=models.IntegerField(default=1, unique=False, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
