# Generated by Django 4.0.5 on 2022-07-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_automation', '0004_remove_roomautomation_room_roomautomation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomautomation',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
