# Generated by Django 4.0.5 on 2022-07-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_automation', '0005_alter_roomautomation_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomautomation',
            options={'ordering': ['number'], 'verbose_name': 'Автоматизация номера', 'verbose_name_plural': 'Автоматизация номеров'},
        ),
    ]
