# Generated by Django 4.0.5 on 2022-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_automation', '0006_alter_roomautomation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomautomation',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Номер'),
        ),
    ]
